---
- name: Add Oracle Java apt repository
  apt_repository: repo="ppa:webupd8team/java"

- name: Upgrade all packages
  apt: upgrade=dist update_cache=yes

- name: Install Git
  apt: name=git state=latest

- name: Accept Oracle License
  debconf: name=oracle-java7-installer question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java
  apt: name=oracle-java7-installer state=latest

- name: Install Maven
  apt: name=maven state=latest

- name: Install MySQL
  apt: name=mysql-server state=latest

- name: Downloading watchtower-common
  git: repo=https://github.com/icclab/watchtower-common.git dest="/home/{{ansible_ssh_user}}/"
  when: not release

- name: Downloading watchtower-common-0.1.0
  get_url: url=https://github.com/icclab/watchtower-common/archive/watchtower-common-0.1.0.tar.gz dest="/home/{{ansible_ssh_user}}/"
  when: release

- name: Unpacking watchtower-common-0.1.0
  unarchive: src="/home/{{ansible_ssh_user}}/watchtower-common-0.1.0.tar.gz" dest="/home/{{ansible_ssh_user}}/" copy=no
  when: release

- name: Install watchtower-common
  command: mvn clean install
  args:
    chdir: "/home/{{ansible_ssh_user}}/watchtower-common"

- name: Downloading watchtower-monitoring
  git: repo=https://github.com/icclab/watchtower-monitoring.git dest="/home/{{ansible_ssh_user}}/"
  when: not release

- name: Downloading latest release of watchtower-monitoring
  get_url: url=https://github.com/icclab/watchtower-monitoring/archive/watchtower-monitoring-0.1.0.tar.gz dest="/home/{{ansible_ssh_user}}/"
  when: release
