---
- name: Add hostname to /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line="127.0.0.1 localhost {{inventory_hostname}}" owner=root group=root mode=0644

- name: Add Oracle Java apt repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Update and upgrade all packages
  apt: upgrade=dist update_cache=yes

- name: Install Git
  apt: name=git state=latest

- name: Install Java
  apt: name=oracle-java7-installer state=latest

- name: Install Maven
  apt: name=maven state=latest

- name: Install MySQL
  apt: name=mysql state=latest

- name: Install watchtower-monitoring
  git: repo=https://github.com/icclab/watchtower-monitoring.git dest=/home/{{ansible_ssh_user}}/
  shell: mvn clean package chdir=/home/{{ansible_ssh_user}}/watchtower-monitoring
  when: not release

- name: Install latest release of watchtower-monitoring
  get_url: url=https://github.com/icclab/watchtower-monitoring/archive/watchtower-monitoring-0.1.0.tar.gz dest=/home/{{ansible_ssh_user}}/
  when: release
